#!/bin/bash
#
# make-new-nx - generate new nx-lang directory
#

srcdir=$(dirname $(readlink -f "$0"))
dstdir=$1
x=$1
nx="nx-$1"
X=$1

if [ ! -d $dstdir ]; then 
    echo "yuck"
    exit 1
fi

function trans () {
    src=$srcdir/$1
    dst=$dstdir/$1
    sed -e "s/@x@/$x/g" -e "s/@X@/$X/g" < $src > $dst
}

if [ ! -f $dstdir/compile-tree-il.scm ]; then
    trans compile-tree-il.scm
else
    echo "compile-tree-il.scm exists already"
fi

if [ ! -f $dstdir/xlib.scm ]; then
    trans xlib.scm
else
    echo "$dstdir/xlib.scm exists already"
fi

if [ ! -f dstdir/nx$x ]; then
    src=$srcdir/nxtmpl
    dst=$dstdir/nx$x
    sed -e "s/@x@/$x/g" -e "s/@X@/$X/g" < $src > $dst
else
    echo "$dstdir/nx$x exists already"
fi

# --- last line ---
