\input texinfo.tex
@setfilename c99-hg.info
@settitle C99 User's Guide

@copying
Copyright (C) 2017 -- Matthew R. Wette.

Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3 or
any later version published by the Free Software Foundation; with no
Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.  A
copy of the license is included with the distribution as COPYING.DOC.
@end copying

@clear skip

@titlepage
@title C99 Parser User's Guide
@subtitle rough and incomplete

@vskip 0pt plus 1filll
@quotation
Copyright @copyright{} 2017 -- Matthew R. Wette.

Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3 or
any later version published by the Free Software Foundation; with no
Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.  A
copy of the license is included with the distribution as COPYING.DOC.
@end quotation
@author Matt Wette
@end titlepage

@ifnottex
@node Top, Introduction, (dir), (dir)
@top Introduction
@end ifnottex

@menu
* Introduction ::
@end menu

@node Introduction
@chapter The Introduction

This is a manual for ...

Note on CPP replacement text: IIRC, C99 will remove comments from CPP
statements before processing.  I preserve this and remove inside the
CPP parser.

@subsubsection Include Helpers

The C99 parsers can use ``include helpers''.  This allows files to be
parsed without reading full include files.  The user provides
typenames (types defined using @code{typedef}) and defines.  The
syntax for the include-helper optional argument to the parsers is
@example
(define my-inc-helper
 '(("foo.h" "foo_t" "ABC=123" "SUM(X,Y)=((X)+(Y))")
   ("bar.h" "bar_t" "DEF=456" "MAX(X,Y)=((X)>(Y)?(X):(Y))"))
@end example

The C99 @code{parser} and @code{xparser} modules export @code{c99-std-help}.

@chapter Administrative Notes

@section The Free Documentation License
The Free Documentation License is included in the Guile Reference
Manual.  It is included with the @sc{nyacc} source as COPYING.DOC.

@bye
@c --- last line
