# nyacc/lang/c99/Makefile.nyacc
#
# Copyright (C) 2016 Matthew R. Wette
# 
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.

SUBDIRS = 

TESTS_ENVIRONMENT = \
	GUILE_LOAD_PATH= GUILE_AUTO_COMPILE=0 \
	$(GUILE) -L `pwd`/../../../../module -L `pwd`/../../..

TESTS = \
	c99-01.test				\
	c99-02.test				\
	c99-03.test				\
	c99-04.test				\
	c99-05.test				\
	#

check: check-TESTS

check-TESTS: $(TESTS)
	@for test in $(TESTS); do \
	  $(TESTS_ENVIRONMENT) $$test; \
	done
	@for dir in $(SUBDIRS); do \
	  (cd $$dir; \
	   make -f Makefile.nyacc GUILE=$(GUILE) GUILD=$(GUILD) check-TESTS); \
	done

# --- last line ---
