;; auto-generated by ffi-help.scm

(define-module (gdbm)
  #:use-module (system ffi-help-rt)
  #:use-module ((system foreign) #:prefix ffi:)
  #:use-module (bytestructures guile)
  )
(dynamic-link "libgdbm")

;; typedef unsigned long long int gdbm_count_t;

;; typedef struct {
;;   char *dptr;
;;   int dsize;
;; } datum;
(define datum-desc
  (bs:struct
    (list `(dptr ,(bs:pointer int)) `(dsize ,int))))
(export datum-desc)
(define-fh-compound-type/p datum datum-desc)

;; typedef struct gdbm_file_info *GDBM_FILE;
(define-fh-pointer-type GDBM_FILE)

;; extern const char *gdbm_version;
(define gdbm_version (dynamic-pointer "gdbm_version" (dynamic-link)))

;; extern int const gdbm_version_number[3];
(define gdbm_version_number-desc
  (bs:vector 3 int)
  )
(define gdbm_version_number
  (bytestructure
    gdbm_version_number-desc
    (ffi:pointer->bytevector
      (dynamic-pointer
        "gdbm_version_number"
        (dynamic-link))
      (bytestructure-descriptor-size
        gdbm_version_number-desc))))

;; extern GDBM_FILE gdbm_fd_open(int fd, const char *file_name, int block_size
;;     , int flags, void (*fatal_func)(const char *));
(define gdbm_fd_open
  (let ((~f (ffi:pointer->procedure
              '*
              (dynamic-func "gdbm_fd_open" (dynamic-link))
              (list ffi:int '* ffi:int ffi:int '*))))
    (lambda (fd file_name block_size flags fatal_func)
      (let ((~fd (unwrap~fixed fd))
            (~file_name (unwrap~pointer file_name))
            (~block_size (unwrap~fixed block_size))
            (~flags (unwrap~fixed flags))
            (~fatal_func
              ((make-ftn-arg-unwrapper ffi:void (list '*))
               fatal_func)))
        (wrap-GDBM_FILE
          (~f ~fd
              ~file_name
              ~block_size
              ~flags
              ~fatal_func))))))
(export gdbm_fd_open)

;; extern GDBM_FILE gdbm_open(const char *, int, int, int, void (*)(const char
;;      *));
(define gdbm_open
  (let ((~f (ffi:pointer->procedure
              '*
              (dynamic-func "gdbm_open" (dynamic-link))
              (list '* ffi:int ffi:int ffi:int '*))))
    (lambda (@11218 arg-1 arg-2 arg-3 @11216)
      (let ((~@11218 (unwrap~pointer @11218))
            (~arg-1 (unwrap~fixed arg-1))
            (~arg-2 (unwrap~fixed arg-2))
            (~arg-3 (unwrap~fixed arg-3))
            (~@11216
              ((make-ftn-arg-unwrapper ffi:void (list '*))
               @11216)))
        (wrap-GDBM_FILE
          (~f ~@11218 ~arg-1 ~arg-2 ~arg-3 ~@11216))))))
(export gdbm_open)

;; extern void gdbm_close(GDBM_FILE);
(define gdbm_close
  (let ((~f (ffi:pointer->procedure
              ffi:void
              (dynamic-func "gdbm_close" (dynamic-link))
              (list '*))))
    (lambda (arg-0)
      (let ((~arg-0 (unwrap-GDBM_FILE arg-0)))
        (~f ~arg-0)))))
(export gdbm_close)

;; extern int gdbm_store(GDBM_FILE, datum, datum, int);
(define gdbm_store
  (let ((~f (ffi:pointer->procedure
              ffi:int
              (dynamic-func "gdbm_store" (dynamic-link))
              (list '*
                    (list '* ffi:int)
                    (list '* ffi:int)
                    ffi:int))))
    (lambda (arg-0 arg-1 arg-2 arg-3)
      (let ((~arg-0 (unwrap-GDBM_FILE arg-0))
            (~arg-1 (unwrap-datum arg-1))
            (~arg-2 (unwrap-datum arg-2))
            (~arg-3 (unwrap~fixed arg-3)))
        (~f ~arg-0 ~arg-1 ~arg-2 ~arg-3)))))
(export gdbm_store)

;; extern datum gdbm_fetch(GDBM_FILE, datum);
(define gdbm_fetch
  (let ((~f (ffi:pointer->procedure
              (list '* ffi:int)
              (dynamic-func "gdbm_fetch" (dynamic-link))
              (list '* (list '* ffi:int)))))
    (lambda (arg-0 arg-1)
      (let ((~arg-0 (unwrap-GDBM_FILE arg-0))
            (~arg-1 (unwrap-datum arg-1)))
        (wrap-datum (~f ~arg-0 ~arg-1))))))
(export gdbm_fetch)

;; extern int gdbm_delete(GDBM_FILE, datum);
(define gdbm_delete
  (let ((~f (ffi:pointer->procedure
              ffi:int
              (dynamic-func "gdbm_delete" (dynamic-link))
              (list '* (list '* ffi:int)))))
    (lambda (arg-0 arg-1)
      (let ((~arg-0 (unwrap-GDBM_FILE arg-0))
            (~arg-1 (unwrap-datum arg-1)))
        (~f ~arg-0 ~arg-1)))))
(export gdbm_delete)

;; extern datum gdbm_firstkey(GDBM_FILE);
(define gdbm_firstkey
  (let ((~f (ffi:pointer->procedure
              (list '* ffi:int)
              (dynamic-func "gdbm_firstkey" (dynamic-link))
              (list '*))))
    (lambda (arg-0)
      (let ((~arg-0 (unwrap-GDBM_FILE arg-0)))
        (wrap-datum (~f ~arg-0))))))
(export gdbm_firstkey)

;; extern datum gdbm_nextkey(GDBM_FILE, datum);
(define gdbm_nextkey
  (let ((~f (ffi:pointer->procedure
              (list '* ffi:int)
              (dynamic-func "gdbm_nextkey" (dynamic-link))
              (list '* (list '* ffi:int)))))
    (lambda (arg-0 arg-1)
      (let ((~arg-0 (unwrap-GDBM_FILE arg-0))
            (~arg-1 (unwrap-datum arg-1)))
        (wrap-datum (~f ~arg-0 ~arg-1))))))
(export gdbm_nextkey)

;; extern int gdbm_reorganize(GDBM_FILE);
(define gdbm_reorganize
  (let ((~f (ffi:pointer->procedure
              ffi:int
              (dynamic-func "gdbm_reorganize" (dynamic-link))
              (list '*))))
    (lambda (arg-0)
      (let ((~arg-0 (unwrap-GDBM_FILE arg-0)))
        (~f ~arg-0)))))
(export gdbm_reorganize)

;; extern void gdbm_sync(GDBM_FILE);
(define gdbm_sync
  (let ((~f (ffi:pointer->procedure
              ffi:void
              (dynamic-func "gdbm_sync" (dynamic-link))
              (list '*))))
    (lambda (arg-0)
      (let ((~arg-0 (unwrap-GDBM_FILE arg-0)))
        (~f ~arg-0)))))
(export gdbm_sync)

;; extern int gdbm_exists(GDBM_FILE, datum);
(define gdbm_exists
  (let ((~f (ffi:pointer->procedure
              ffi:int
              (dynamic-func "gdbm_exists" (dynamic-link))
              (list '* (list '* ffi:int)))))
    (lambda (arg-0 arg-1)
      (let ((~arg-0 (unwrap-GDBM_FILE arg-0))
            (~arg-1 (unwrap-datum arg-1)))
        (~f ~arg-0 ~arg-1)))))
(export gdbm_exists)

;; extern int gdbm_setopt(GDBM_FILE, int, void *, int);
(define gdbm_setopt
  (let ((~f (ffi:pointer->procedure
              ffi:int
              (dynamic-func "gdbm_setopt" (dynamic-link))
              (list '* ffi:int '* ffi:int))))
    (lambda (arg-0 arg-1 @11230 arg-3)
      (let ((~arg-0 (unwrap-GDBM_FILE arg-0))
            (~arg-1 (unwrap~fixed arg-1))
            (~@11230 (unwrap~pointer @11230))
            (~arg-3 (unwrap~fixed arg-3)))
        (~f ~arg-0 ~arg-1 ~@11230 ~arg-3)))))
(export gdbm_setopt)

;; extern int gdbm_fdesc(GDBM_FILE);
(define gdbm_fdesc
  (let ((~f (ffi:pointer->procedure
              ffi:int
              (dynamic-func "gdbm_fdesc" (dynamic-link))
              (list '*))))
    (lambda (arg-0)
      (let ((~arg-0 (unwrap-GDBM_FILE arg-0)))
        (~f ~arg-0)))))
(export gdbm_fdesc)

;; extern int gdbm_export(GDBM_FILE, const char *, int, int);
(define gdbm_export
  (let ((~f (ffi:pointer->procedure
              ffi:int
              (dynamic-func "gdbm_export" (dynamic-link))
              (list '* '* ffi:int ffi:int))))
    (lambda (arg-0 @11234 arg-2 arg-3)
      (let ((~arg-0 (unwrap-GDBM_FILE arg-0))
            (~@11234 (unwrap~pointer @11234))
            (~arg-2 (unwrap~fixed arg-2))
            (~arg-3 (unwrap~fixed arg-3)))
        (~f ~arg-0 ~@11234 ~arg-2 ~arg-3)))))
(export gdbm_export)

;; extern int gdbm_export_to_file(GDBM_FILE dbf, FILE *fp);
(define gdbm_export_to_file
  (let ((~f (ffi:pointer->procedure
              ffi:int
              (dynamic-func
                "gdbm_export_to_file"
                (dynamic-link))
              (list '* '*))))
    (lambda (dbf fp)
      (let ((~dbf (unwrap-GDBM_FILE dbf)))
        (~f ~dbf fp)))))
(export gdbm_export_to_file)

;; extern int gdbm_import(GDBM_FILE, const char *, int);
(define gdbm_import
  (let ((~f (ffi:pointer->procedure
              ffi:int
              (dynamic-func "gdbm_import" (dynamic-link))
              (list '* '* ffi:int))))
    (lambda (arg-0 @11238 arg-2)
      (let ((~arg-0 (unwrap-GDBM_FILE arg-0))
            (~@11238 (unwrap~pointer @11238))
            (~arg-2 (unwrap~fixed arg-2)))
        (~f ~arg-0 ~@11238 ~arg-2)))))
(export gdbm_import)

;; extern int gdbm_import_from_file(GDBM_FILE dbf, FILE *fp, int flag);
(define gdbm_import_from_file
  (let ((~f (ffi:pointer->procedure
              ffi:int
              (dynamic-func
                "gdbm_import_from_file"
                (dynamic-link))
              (list '* '* ffi:int))))
    (lambda (dbf fp flag)
      (let ((~dbf (unwrap-GDBM_FILE dbf))
            (~flag (unwrap~fixed flag)))
        (~f ~dbf fp ~flag)))))
(export gdbm_import_from_file)

;; extern int gdbm_count(GDBM_FILE dbf, gdbm_count_t *pcount);
(define gdbm_count
  (let ((~f (ffi:pointer->procedure
              ffi:int
              (dynamic-func "gdbm_count" (dynamic-link))
              (list '* '*))))
    (lambda (dbf pcount)
      (let ((~dbf (unwrap-GDBM_FILE dbf)))
        (~f ~dbf pcount)))))
(export gdbm_count)

;; typedef struct gdbm_recovery_s {
;;   /* Input members.
;;        These are initialized before call to gdbm_recover.  The flags argument
;;       
;;        specifies which of them are initialized. */
;;   void (*errfun)(void *data, char const *fmt, ...);
;;   void *data;
;;   size_t max_failed_keys;
;;   size_t max_failed_buckets;
;;   size_t max_failures;
;;   /* Output members.
;;        The gdbm_recover function fills these before returning. */
;;   size_t recovered_keys;
;;   size_t recovered_buckets;
;;   size_t failed_keys;
;;   size_t failed_buckets;
;;   char *backup_name;
;; } gdbm_recovery;
(define gdbm_recovery-desc
  (bs:struct
    (list `(errfun ,(bs:pointer intptr_t))
          `(data ,(bs:pointer intptr_t))
          `(max_failed_keys ,size_t-desc)
          `(max_failed_buckets ,size_t-desc)
          `(max_failures ,size_t-desc)
          `(recovered_keys ,size_t-desc)
          `(recovered_buckets ,size_t-desc)
          `(failed_keys ,size_t-desc)
          `(failed_buckets ,size_t-desc)
          `(backup_name ,(bs:pointer int)))))
(export gdbm_recovery-desc)
(define-fh-compound-type/p gdbm_recovery gdbm_recovery-desc)
(define struct-gdbm_recovery_s gdbm_recovery)

;; extern int gdbm_recover(GDBM_FILE dbf, gdbm_recovery *rcvr, int flags);
(define gdbm_recover
  (let ((~f (ffi:pointer->procedure
              ffi:int
              (dynamic-func "gdbm_recover" (dynamic-link))
              (list '* '* ffi:int))))
    (lambda (dbf rcvr flags)
      (let ((~dbf (unwrap-GDBM_FILE dbf))
            (~rcvr (unwrap-gdbm_recovery* rcvr))
            (~flags (unwrap~fixed flags)))
        (~f ~dbf ~rcvr ~flags)))))
(export gdbm_recover)

;; extern int gdbm_dump(GDBM_FILE, const char *, int fmt, int open_flags, int 
;;     mode);
(define gdbm_dump
  (let ((~f (ffi:pointer->procedure
              ffi:int
              (dynamic-func "gdbm_dump" (dynamic-link))
              (list '* '* ffi:int ffi:int ffi:int))))
    (lambda (arg-0 @11246 fmt open_flags mode)
      (let ((~arg-0 (unwrap-GDBM_FILE arg-0))
            (~@11246 (unwrap~pointer @11246))
            (~fmt (unwrap~fixed fmt))
            (~open_flags (unwrap~fixed open_flags))
            (~mode (unwrap~fixed mode)))
        (~f ~arg-0 ~@11246 ~fmt ~open_flags ~mode)))))
(export gdbm_dump)

;; extern int gdbm_dump_to_file(GDBM_FILE, FILE *, int fmt);
(define gdbm_dump_to_file
  (let ((~f (ffi:pointer->procedure
              ffi:int
              (dynamic-func "gdbm_dump_to_file" (dynamic-link))
              (list '* '* ffi:int))))
    (lambda (arg-0 @11249 fmt)
      (let ((~arg-0 (unwrap-GDBM_FILE arg-0))
            (~fmt (unwrap~fixed fmt)))
        (~f ~arg-0 @11249 ~fmt)))))
(export gdbm_dump_to_file)

;; extern int gdbm_load(GDBM_FILE *, const char *, int replace, int meta_flags
;;     , unsigned long *line);
(define gdbm_load
  (let ((~f (ffi:pointer->procedure
              ffi:int
              (dynamic-func "gdbm_load" (dynamic-link))
              (list '* '* ffi:int ffi:int '*))))
    (lambda (@11254 @11253 replace meta_flags line)
      (let ((~@11254 (unwrap-GDBM_FILE* @11254))
            (~@11253 (unwrap~pointer @11253))
            (~replace (unwrap~fixed replace))
            (~meta_flags (unwrap~fixed meta_flags))
            (~line (unwrap~pointer line)))
        (~f ~@11254 ~@11253 ~replace ~meta_flags ~line)))))
(export gdbm_load)

;; extern int gdbm_load_from_file(GDBM_FILE *, FILE *, int replace, int 
;;     meta_flags, unsigned long *line);
(define gdbm_load_from_file
  (let ((~f (ffi:pointer->procedure
              ffi:int
              (dynamic-func
                "gdbm_load_from_file"
                (dynamic-link))
              (list '* '* ffi:int ffi:int '*))))
    (lambda (@11259 @11258 replace meta_flags line)
      (let ((~@11259 (unwrap-GDBM_FILE* @11259))
            (~replace (unwrap~fixed replace))
            (~meta_flags (unwrap~fixed meta_flags))
            (~line (unwrap~pointer line)))
        (~f ~@11259 @11258 ~replace ~meta_flags ~line)))))
(export gdbm_load_from_file)

;; extern int gdbm_copy_meta(GDBM_FILE dst, GDBM_FILE src);
(define gdbm_copy_meta
  (let ((~f (ffi:pointer->procedure
              ffi:int
              (dynamic-func "gdbm_copy_meta" (dynamic-link))
              (list '* '*))))
    (lambda (dst src)
      (let ((~dst (unwrap-GDBM_FILE dst))
            (~src (unwrap-GDBM_FILE src)))
        (~f ~dst ~src)))))
(export gdbm_copy_meta)

;; typedef int gdbm_error;

;; extern gdbm_error gdbm_errno;
(define gdbm_errno-desc
  gdbm_error-desc
  )
(define gdbm_errno
  (bytestructure
    gdbm_errno-desc
    (ffi:pointer->bytevector
      (dynamic-pointer "gdbm_errno" (dynamic-link))
      (bytestructure-descriptor-size gdbm_errno-desc))))

;; extern const char *constgdbm_errlist[];
