;; auto-generated by ffi-help.scm

(define-module (test)
  #:use-module (system ffi-help-rt)
  #:use-module ((system foreign) #:prefix ffi:)
  #:use-module (bytestructures guile)
  )
(dynamic-link "libintl")
(dynamic-link "libglib-2.0")

;; access to enum symbols and #define'd constants:
(define test-symbol-val
  (let ((sym-tab '()))
    (lambda (k) (assq-ref sym-tab k))))
(export test-symbol-val)

(define (unwrap-enum obj)
  (cond ((number? obj) obj)
        ((symbol? obj) (test-symbol-val obj))
        ((fh-object? obj) (struct-ref obj 0))
        (else (error "type mismatch"))))

(define test-types
  ())
(export test-types)

;; --- last line ---
